server:
  port: 8788

spring:
  application:
    name: admin-server

  profiles:
    active: dev

  jackson:
    property-naming-strategy: SNAKE_CASE

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml