server:
  port: 8188

spring:
  application:
    name: sink-server

  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml

# todo: 路径
geo-ip:
  file-path: /Users/heqin/workspace/java/user-behaviour-analysis/sink-server/src/main/resources/Geo-IP/Country.mmdb