spring:
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      max-lifetime: 540000
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000

    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/user_behaviour_analysis
          username: root
          password: 5323105
          driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        min-idle: 0
        max-active: 8
        max-idle: 8
        max-wait: 300ms
    connect-timeout: 30000ms

  kafka:
    # 指定kafka server的地址，集群配多个，中间，逗号隔开
    bootstrap-servers: 127.0.0.1:9092
    # 生产者
    producer:
      # 写入失败时，重试次数。当leader节点失效，一个repli节点会替代成为leader节点，此时可能出现写入失败，
      # 当retris为0时，produce不会重复。retirs重发，此时repli节点完全成为leader节点，不会产生消息丢失。
      retries: 3
      # 每次批量发送消息的数量,produce积累到一定数据，一次发送
      batch-size: 16384
      # produce积累数据一次发送，缓存大小达到buffer.memory就发送数据
      buffer-memory: 33554432
      # 指定消息key和消息体的编解码方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger.ms: 1
      # ack: 1 生产者会在消息被成功写入到主题的一个分区后得到服务器的确认
      acks: 1

    # 消费者
    consumer:
      enable-auto-commit: false
      auto-commit-interval: 100ms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        session.timeout.ms: 15000
      group-id: dev-group
      auto-offset-reset: latest
      max-poll-records: 100
    listener:
      ack-mode: manual_immediate

data-source:
  doris:
    url: jdbc:mysql://localhost:9030/user_behaviour_analysis?rewriteBatchedStatements=true
    username: root
    password:
    driver: com.mysql.cj.jdbc.Driver
    db-name: user_behaviour_analysis

  mysql:
    url: jdbc:mysql://localhost:3306/user_behaviour_analysis?rewriteBatchedStatements=true
    username: root
    password: 5323105
    driver: com.mysql.cj.jdbc.Driver

management:
  metrics:
    export:
      prometheus:
        enabled: true

  endpoints:
    web:
      exposure:
        include: "*"

kafka:
  topics:
    online-log: log-sink